language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v6
  - v5
  - v4
  - v0.12
  - v0.10
before_script:
  - npm prune
script:
  - npm run test:lint
  - npm run test:coverage
after_success:
  - npm run semantic-release
